name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v3
    
    - name: Configue AWS credentials
      uses: aws-actions/configure-aws-cred@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/z5n5d8t1

    - name: Build, tag and push the Docker-Image
      run: |
        docker build . -t docker-php-image:$(date +%s)
        docker tag aws-docker-image-php:latest public.ecr.aws/z5n5d8t1/aws-docker-image-php:latest
        docker push public.ecr.aws/z5n5d8t1/aws-docker-image-php:latest
